import OpenAI from "openai";

import { type ChallengeSuggestion, type ModerationStatus } from "@/lib/types";

const moderationModel = process.env.OPENAI_MODERATION_MODEL ?? "gpt-4.1-mini";
const suggestionModel = process.env.OPENAI_SUGGESTION_MODEL ?? "gpt-4.1-mini";

function getClient() {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return null;
  }
  return new OpenAI({ apiKey });
}

export function hasOpenAIConfig() {
  return Boolean(process.env.OPENAI_API_KEY);
}

function extractJson(text: string) {
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) {
    throw new Error("Model response did not contain JSON.");
  }
  return JSON.parse(text.slice(start, end + 1)) as Record<string, unknown>;
}

export async function moderateSubmissionImage(input: { challenge: string; imageDataUrl: string }) {
  const client = getClient();
  if (!client) {
    return {
      moderationStatus: "approved" as ModerationStatus,
      reviewNotes: "OpenAI moderation unavailable; fell back to basic mime/type checks."
    };
  }

  const completion = await client.chat.completions.create({
    model: moderationModel,
    response_format: { type: "json_object" },
    messages: [
      {
        role: "system",
        content: "You review scaveng.io submissions for inappropriate or unsafe content only. Wrong subject is not a rejection reason. Return strict JSON with keys moderationStatus and reviewNotes. moderationStatus must be approved, flagged, or blocked. Use blocked only for clearly inappropriate, unsafe, explicit, or abusive content. Use flagged for ambiguous, non-photo, or unreadable images."
      },
      {
        role: "user",
        content: [
          { type: "text", text: `Challenge: ${input.challenge}` },
          { type: "text", text: "Decide whether this image is approved, flagged, or blocked under a broad public consumer app safety standard." },
          { type: "image_url", image_url: { url: input.imageDataUrl } }
        ]
      }
    ]
  });

  const payload = extractJson(completion.choices[0]?.message?.content ?? "{}");
  const moderationStatus = String(payload.moderationStatus ?? "flagged");
  const normalized = moderationStatus === "approved" || moderationStatus === "blocked" ? moderationStatus : "flagged";
  return {
    moderationStatus: normalized as ModerationStatus,
    reviewNotes: String(payload.reviewNotes ?? "OpenAI moderation review completed.")
  };
}

export async function generateChallengeSuggestions(input: { count: number; existingTitles: string[] }) {
  const client = getClient();
  if (!client) {
    return fallbackSuggestions(input.count);
  }

  const completion = await client.chat.completions.create({
    model: suggestionModel,
    response_format: { type: "json_object" },
    messages: [
      {
        role: "system",
        content: "You write mobile-friendly daily scavenger hunt prompts. Return strict JSON with a suggestions array. Each suggestion must have title and rationale. Keep prompts globally understandable, safe, non-qualitative, image-friendly, and completable within one hour. Avoid duplicates or anything requiring niche access."
      },
      {
        role: "user",
        content: `Generate ${input.count} concise scavenger hunt challenges. Avoid these existing titles: ${input.existingTitles.join(", ") || "none"}.`
      }
    ]
  });

  const payload = extractJson(completion.choices[0]?.message?.content ?? "{}");
  const suggestions = Array.isArray(payload.suggestions) ? payload.suggestions : [];
  return suggestions
    .slice(0, input.count)
    .map((suggestion, index) => ({
      id: `ai-${Date.now()}-${index}`,
      title: String((suggestion as Record<string, unknown>).title ?? `Suggestion ${index + 1}`),
      rationale: String((suggestion as Record<string, unknown>).rationale ?? "Generated by OpenAI."),
      sourceModel: suggestionModel,
      approved: false
    } satisfies ChallengeSuggestion));
}

function fallbackSuggestions(count: number) {
  const seed = [
    { title: "Find a handwritten grocery list", rationale: "Common household object with low safety risk and easy judging." },
    { title: "Find a striped umbrella", rationale: "Distinct visual target that works well in a phone photo." },
    { title: "Find a yellow mug", rationale: "Simple object challenge with broad availability and fast verification." },
    { title: "Find a paper map", rationale: "Clear visual cue that stays easy to verify by glance." }
  ];

  return seed.slice(0, count).map((item, index) => ({
    id: `fallback-${index}`,
    title: item.title,
    rationale: item.rationale,
    sourceModel: "fallback",
    approved: false
  } satisfies ChallengeSuggestion));
}